config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/user/items/create'

  get '/users/login' => 'sessions#new'
  post '/users/login' => 'sessions#create'
  get '/users/signup' => 'users#new'
  post '/users/signup' => 'users#create'
  get '/logout' => 'sessions#destroy'

  # get '/users/time' => 'users#time'
  resources :users, except: [:new, :create] do
    resources :lists do
      resources :items
      resources :tags
    end
  end

  root 'static#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/concerns/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  accepts_nested_attributes_for :user, reject_if: proc { |attributes| attributes['username'].blank? }
end

app/models/concerns/post.rb
class Post < ActiveRecord::Base
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :comments
  has_many :users, through: :comments

  accepts_nested_attributes_for :categories

  def categories_attributes=(category_attributes)
      category_attributes.values.each do |category_attribute|
        category = Category.find_or_create_by(category_attribute)
        self.categories << category
      end
  end
end

app/models/concerns/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/concerns/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts, through: :comments
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items
  has_many :list_tags
  has_many :tags, through: :list_tags

  validates :name, :presence => true

  def self.my_users_items(userid)
    list = List.all.where(user_id: userid)
    list.map do |list|
      list.items
    end
  end
end

app/models/list_tag.rb
class ListTag < ActiveRecord::Base
  belongs_to :list
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :list_tags
  has_many :lists, through: :list_tags

  validates :name, :presence => true, uniqueness: true

  def date=(date)
  end

  def date
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists

  has_secure_password
  # validates :name, :password_digest, :presence => true
  validates :name, :password, :presence => true

  def self.find_or_create_by_omniauth(auth_hash)
    oauth_nickname = auth_hash["info"]["nickname"]
    self.where(:name => oauth_nickname).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(:name => auth_hash["info"]["nickname"]).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_logged_in, :logged_in?, :current_user_name, :current_user_level

  def logged_in?
    !!session[:user_id] && User.find(session[:user_id])
  end

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def current_user_name
    current_user.name
  end

  def current_user_level
    if current_user
      current_user.level
    else
      0
    end
  end

  def require_logged_in
    redirect_to controller: 'sessions', action: 'new' unless current_user
  end
end

app/controllers/concerns/static_controller.rb
class StaticController < ApplicationController
  def index
    render :index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    redirect_to "/users/#{params[:user_id]}/lists/#{params[:list_id]}"
  end

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      respond_to do |f|
        f.json{render :json => @item}
        f.html{redirect_to user_list_path(@item.list.user,@item.list)}
      end
    else
      render user_list_path(@list.user, @list)
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to user_list_path(@item.list.user, @item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    newlevel = @item.list.user.level += 1
    @item.list.user.update_attribute(:level, newlevel)
    @item.destroy
    render json: @item
  end

  private
    def item_params
      params.require(:item).permit(:description, :status)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action  :require_logged_in

  def time
    raise params.inspect
  end

  def index
    if @user = User.find_by(id: session[:user_id])
      @list = List.new # item for form to wrap around
      @lists = @user.lists
    else
      redirect_to "/users/login"
    end
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @list = List.find(params[:id])
    @item = Item.new #item tag is empty: set up for form_for tag to wrap around
    @tag = Tag.new
    @tags = @list.tags
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @list}
    end
  end

  def create
    @user = User.find_by(id: session[:user_id])
    @list = @user.lists.create(list_params)
    if @list.save
      redirect_to "/users/#{@user.id}/lists/#{@list.id}"
    else
      @lists = @user.lists
      render :index
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    render json: @list
  end

  private
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}/lists"
      return
    end

    @user = User.find_by(name: params[:name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}/lists"
    else
      redirect_to "/users/signup"
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    redirect_to "/users/#{params[:user_id]}/lists/#{params[:list_id]}"
  end

  def create
    @list = List.find(params[:list_id], params[:user_id])# has user_id
    @tag = Tag.new(tag_params)
    if @tag.save
      @list_tag = ListTag.create(tag_id: @tag.id, list_id: params[:list_id])
      redirect_to "/users/#{params[:user_id]}/lists/#{params[:list_id]}"
    else
        redirect_to "/users/#{params[:user_id]}/lists/#{params[:list_id]}"
    end
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.create(user_params)
    if User.find_by(:name => params[:user][:name]) || @user.valid?
      session[:user_id] = @user.id
      redirect_to "/"
    else
      redirect_to "/users/signup"
    end
  end

  def show
    if !@user
      redirect_to "/users/login"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item_li.html.erb
<div id ="<%='item-text' + item.id.to_s %>">
  <div class="row">
    <label class="col"><%= item.description %></label>
      <%= form_tag(user_list_item_path(item.list.user,item.list, item), :method => :delete, :class => "destroy_button" ) do %>
        <button type="submit" class="x-destroy">X</button>
      <%end%>
  </div>
</div>

app/views/items/show.html.erb
<div id ="<%='item-text' + @item.id.to_s %>">
  <div class="row">
    <label class="col"><%= @item.description %></label>
      <%= form_tag(user_list_item_path(@item.list.user,@item.list, @item), :method => :delete, :class => "destroy_button" ) do %>
        <button type="submit" class="x-destroy">X</button>
      <%end%>
  </div>
</div>
<!-- lists show -->
<!-- this is for when im not using handlebars and in item#create i just render this page-->

app/views/lists/index.html.erb
<div class="container-fluid padding">
  <h1 class="pt-5 pb-3">Your Lists</h1>
  <%= form_for([@user, @list]) do |f| %>
    <%= f.text_field :name, :class => "pt-3 pb-3 text-center enter_new_item", :placeholder => ("enter a new list") %>
    <%= f.submit :class => "no_style" %>
  <% end %>
</div>

<section class="main text-left">
  <div class="all-things-inlist">
    <% @lists.each do |list| %>
      <div id="<%='list-text' + list.id.to_s %>">
        <div class="row">
          <label><%= link_to list.name, user_list_path(id: list.id, user_id: @user.id) %></label>
            <%= form_tag(user_list_path(id: list.id, user_id: @user.id), :method => :delete, :class => "destroy_button float-right" ) do %>
            <button type="submit" class="x-destroy">X</button>
          <%end%>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/lists/show.html.erb
<div class="container-fluid padding">
  <h1 class="pt-5 pb-3"><%= @list.name %></h1>
    <%= form_for [@list, @item], :url => user_list_items_path(user_id: @list.user_id, list_id: @list.id) do |f| %>
    <%= f.text_field :description, :class => "pt-3 pb-3 text-center enter_new_item", :placeholder =>
    (@item.errors.full_messages_for(:description).first || "enter a new item...") %>
    <%= f.submit :style => "display: none", data: { disable_with: false } %>
  <% end %>
</div>

<section class="main text-left">
  <div class="all-things-inlist">
    <%= render :collection => @list.items, :partial => "items/item_li", :as => :item %>
  </div>
</section>

<!-- handlebars template for items -->
  <script id="item-template" type="text/x-handlebars-template">
    <div id="item-text{{id}}">
      <div class="row">
        <label class="col">{{description}}</label>
          <form class="destroy_button" action="/users/<%=@list.user_id%>/lists/<%=@list.id%>/items/{{id}}" accept-charset="UTF-8" method="post">
            <input name="utf8" type="hidden" value="✓">
            <input type="hidden" name="_method" value="delete">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button type="submit" class="x-destroy">X</button>
          </form>
        </div>
    </div>
  </script>
</div>

app/views/users/items.html.erb
<h1>User's Items</h1>
<ul>

<%@user_items.each do |item|%>
    <li><%=item.description%></li>
<%end%>
<ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="text-center">
<%= form_for :user, url: '/users/signup' do |f| %>
  <%= f.label "username" %><br>
  <%= f.text_field :name %><br>
  <%= f.label "password" %><br>
  <%= f.text_field :password %><br><br>

  <%= f.submit "Sign Up" %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Hello, <%= @user.name %>!</h1>